### ISSUE TITLE
Invalid card Type

### ISSUE THREAD

**Issue by acedesigns** [mcred/detect-credit-card-type#1]
Hey @mcred 

I would advise u update you `isMasterCard` method

`$card = '2221000000000009'` returns invalid card

**MasterCard**: `^5[1-5][0-9]{5,}|222[1-9][0-9]{3,}|22[3-9][0-9]{4,}|2[3-6][0-9]{5,}|27[01][0-9]{4,}|2720[0-9]{3,}$` Before 2016, MasterCard numbers start with the numbers 51 through 55, **but this will only detect MasterCard credit cards**; there are other cards issued using the MasterCard system that do not fall into this IIN range. In 2016, they will add numbers in the range (222100-272099).

[Shout Out To senfo](https://stackoverflow.com/a/72801)

### Proposed functions
```php
private function isMasterCard(string $card) :  bool {
        //return preg_match("/^5$|^5[1-5][0-9]{0,14}$/i", $card); // REURNED INVALID CARD
        return preg_match("/^5[1-5][0-9]{5,}|222[1-9][0-9]{3,}|22[3-9][0-9]{4,}|2[3-6][0-9]{5,}|27[01][0-9]{4,}|2720[0-9]{3,}$/i", $card);
 }

private function isDinersClub(string $card) : bool {
        return preg_match("/^3(?:0[0-5]|[68][0-9])[0-9]{4,}$/i", $card);
    }

private function isJCB(string $card) : bool {
        return preg_match("/^(?:2131|1800|35[0-9]{3})[0-9]{3,}$/i", $card);
}
```

## Test Cards

![alt text](https://preview.ibb.co/mUooLm/Screen_Shot_2017_10_24_at_10_40_14.png "Logo Title Text 1")

**Comment by mcred** [comment]
Thanks for the proposed functions. I've updated this in PR #3 and the unit tests are still passing.
